name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: Run conda list
      run: conda list
    - name: Install Python
      shell: cmd
      run: |
        echo %PATH%
        CALL activate.bat
        conda info
        echo %PATH%
        mamba install -y -c conda-forge xtensor
    - name: Install Notebook and widgets
      run: mamba install -y -c notebook ipywidgets
    - name: List the packages
      run: mamba list
